# Generated by Django 5.1.7 on 2025-03-22 03:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='area_image'),
        ),
    ]
