# Generated by Django 5.1.7 on 2025-03-17 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='room_image'),
        ),
    ]
