# Generated by Django 5.1.7 on 2025-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
