# Generated by Django 5.1.7 on 2025-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_rooms_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(default='Room', max_length=100),
        ),
    ]
