# Generated by Django 5.1.7 on 2025-03-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_areas_area_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areas',
            old_name='name',
            new_name='area_name',
        ),
    ]
