# Generated by Django 5.1.7 on 2025-03-14 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
