# Generated by Django 5.1.3 on 2025-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_rename_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='2025-02-26', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
